### ISSUE TITLE
AWS EKS pod: Assembly AWSSDK.SecurityToken could not be found or loaded

### ISSUE THREAD

**Issue by skovsende** [Cimpress-MCP/serilog-sinks-awscloudwatch#110]
When trying to use the sink inside an AWS EKS pod and using a serviceaccount with a role assignment that should give access to cloudwatch, it fails with

`System.InvalidOperationException: Assembly AWSSDK.SecurityToken could not be found or loaded`

when using new AmazonCloudWatchLogsClient() as the cloudWatchClient.

The fix to this is to reference the AWSSDK.SecurityToken nuget package from the application.

Ideally Serilog.Sinks.AwsCloudWatch would reference this package so things "just works", but I get that adding the dependency for a very specific scenario is arguably a bit much. But if not, a note in the documentation might be worth it.

Until someone decides what makes most sense I guess this issue can function as a google result for someone running into a similar issue. :)

**Comment by wparad** [comment]
It suspicious that a dependency that the library isn't using would be required. Is the AWSSDK credential provider dynamically importing this package in a lazy way? The only reason why this package wouldn't be pulled in, is because the AWS SDK credentials package doesn't require it.

Do you have the full stack of the exception message.

Ideally this library doesn't depend on changes to the AWS SDKs for C#, most of these are injectable, so that clients can specify their own versions of these dependencies. It's possible there is a mismatch in a new version of the AWS SDK C# specifically for the CloudWatch client.

Further we of course don't want to include unused direct dependencies in here that can't be validated. But with additional information we can figure out what might be happening.

**Comment by skovsende** [comment]
`
2022-11-07T10:21:08.9073970Z Error initializing log stream. No logs will be sent to AWS CloudWatch. Exception was System.InvalidOperationException: Assembly AWSSDK.SecurityToken could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'AWSSDK.SecurityToken, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'AWSSDK.SecurityToken, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Amazon.Runtime.Internal.ServiceClientHelpers.GetSDKAssembly(String assemblyName)
   at Amazon.Runtime.Internal.ServiceClientHelpers.LoadServiceConfigType(String assemblyName, String serviceConfigClassName)
   at Amazon.Runtime.Internal.ServiceClientHelpers.CreateServiceConfig(String assemblyName, String serviceConfigClassName)
   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.CreateClient()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.CreateClient()
   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.GenerateNewCredentialsAsync()
   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.CreateLogGroupAsync()
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.EnsureInitializedAsync()
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.EmitBatchAsync(IEnumerable`1 events).
`

The only thing I changed from the working solution was to remove the nuget reference to AWSSDK.SecurityToken. I'm looking through the AWSSDK source at the moment to see if they do any funny business - such as loading things dynamically.

**Comment by wparad** [comment]
It looks like it totally is from that stack trace. That's really unfortunate. However it gets me thinking, the only way this would be a problem is if you also don't have any other AWS SDK usage. If you make another reference to a different AWS SDK client and attempt to use it (even this library), don't you get the same issue?

**Comment by skovsende** [comment]
Probably - it might very well be that the missing reference is in the AWSSDK.CloudWatch library - it doesn't seem to have any references when looking at the source code.

And I just checked the AWSSDK code - it sure does use reflection to load things.

**Comment by skovsende** [comment]
Well - AWSSDK.CloudWatch depends on AWSSDK.Core - but nothing else. AWSSDK.SecurityToken also depends on AWSSDK.Core. So it sure seems like AWSSDK.CloudWatch ought to reference AWSSDK.SecurityToken. I'll go make an issue with them instead.

Thanks for your time!

**Comment by wparad** [comment]
If you find out that there's a later version we can depend on to avoid this problem, we'll happily accept a PR to fix that. For the meantime I'm going to close this issue until we find out more.

**Comment by skovsende** [comment]
Sure - I'll get back if I figure something out.

**Comment by skovsende** [comment]
So clearly AWS thinks having a dependency we need to figure out is there is something we should guess ourselves I guess anyone using this sink should remember to reference AWSSDK.SecurityToken if running under a ServiceAccount with AWS privileges in a pod in EKS. That's not for this library to solve. And now at least there is a chance people find a google result when trying to figure out the problem. 

Thanks for the quick reply btw!
