### ISSUE TITLE
StackOverflow on shutdown due to infinite loop with PeriodicBatching changes

### ISSUE THREAD

**Issue by iantoal** [Cimpress-MCP/serilog-sinks-awscloudwatch#133]
Version: 4.2.19

Repro steps:

- Build and run aspnetcore 8.0 app with appsettings based config on dotnet 8 container (image - mcr.microsoft.com/dotnet/sdk:8.0)
- Get the PID of the process (ps aux | grep dotnet)
- Send a SIGTERM to the process (kill -SIGTERM \<pid\>)

Outcome:

Infinite loop until a StackOverflowException throws with the following stack:

...
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.Dispose()
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.Dispose()
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.Dispose()
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.Dispose()
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.Dispose()
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.Dispose()
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.Dispose()
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.Dispose()
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.Dispose()
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.Dispose()
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.Dispose()
   at Serilog.Core.Sinks.RestrictedSink.Dispose()
   at Serilog.LoggerConfiguration+<>c__DisplayClass33_0.<CreateLogger>g__Dispose|1()
   at Serilog.Core.Logger.Dispose()
   at Serilog.Log.CloseAndFlush()
   at Program.\<Main\>$(System.String[])

There's a loop in the disposal code after these changes: https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/commit/cb6ba6104444fb875d2cd34e761aaaac86c80b0c

**Comment by iantoal** [comment]
We probably need some like this in the Dispose code in CloudWatchLogSink.cs:

```
        private bool hasDisposed;
  
        /// <inheritdoc/>
        public void Dispose()
        {
            if (!hasDisposed)
            {
                hasDisposed = true;
                batchingSink.Dispose();
            }
        }

        /// <inheritdoc/>
        public ValueTask DisposeAsync()
        {
            ValueTask task = default;
            if (!hasDisposed)
            {
                hasDisposed = true;
                task = batchingSink.DisposeAsync();
            }

            return task;
        }
```

**Comment by wparad** [comment]
@nblumhardt There seems to be a bug in the PeriodicBatching that calls back dispose on the passed in `IBatchedLogEventSink` creating an infinite loop. The bug seems to be here: https://github.com/serilog/serilog-sinks-periodicbatching/blob/dev/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L237

Any thing you can share on that?

**Comment by nblumhardt** [comment]
Thanks for the ping @wparad - taking a look now 👀
