### ISSUE TITLE
Error while sending the logs to AWSCloudWatch

### ISSUE THREAD

**Issue by shakibmiraki** [Cimpress-MCP/serilog-sinks-awscloudwatch#135]
I get this error while sending the log to aws cloud watch 

Error initializing log stream. No logs will be sent to AWS CloudWatch. Exception was System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream

registering this in the startup and just call log.Error() in controller.

```csharp
public static WebApplicationBuilder AddSerilog(this WebApplicationBuilder webAppBuilder, Action<SerilogConfiguration> configurator)
  {
      SerilogConfiguration config = new();

      if (configurator != null)
      {
          configurator(config);
      }

      var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
      var configuration = new ConfigurationBuilder().AddJsonFile("appsettings.json", false)
                                                    .AddJsonFile($"appsettings.{environment}.json", true)
                                                    .Build();

      SelfLog.Enable(msg => Debug.WriteLine(msg));

      Log.Logger = new LoggerConfiguration()
          .WriteTo.AmazonCloudWatch(new CloudWatchSinkOptions
          {
              LogGroupName = "/RoolzDashboard/Test",
              TextFormatter = new TextFormatter(config.ApplicationType, config.ApplicationName),
              MinimumLogEventLevel = LogEventLevel.Information,
              LogStreamNameProvider = new DefaultLogStreamProvider(),
              CreateLogGroup = true

          }, new AmazonCloudWatchLogsClient("key_id", "secret_key"))
          .WriteTo.Console().CreateLogger();

      webAppBuilder?.Host.UseSerilog();
      return webAppBuilder;
  }
```

**Comment by thoean** [comment]
Can you share your stack trace?

**Comment by shakibmiraki** [comment]
2024-04-14T15:01:45.6353723Z Error initializing log stream. No logs will be sent to AWS CloudWatch. Exception was System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Serilog.Sinks.AwsCloudWatch.PeriodicBatchingSinkImplementationCallback.CreateLogGroupAsync()
   at Serilog.Sinks.AwsCloudWatch.PeriodicBatchingSinkImplementationCallback.EnsureInitializedAsync()
   at Serilog.Sinks.AwsCloudWatch.PeriodicBatchingSinkImplementationCallback.EmitBatchAsync(IEnumerable`1 events).

**Comment by wparad** [comment]
That looks like a problem with the `CredentialsRetriever` which likely means there is problem reading from your OS to fetch the `.aws/credentials` file.

What happens if you manually create the LogGroup, and then set `CreateLogGroup = false`, can you print the stack trace from that error as well?

**Comment by wparad** [comment]
Closing due to lack of additional information.
