### ISSUE TITLE
Sequence Token is re-used in some cases, causing errors posting logs

### ISSUE THREAD

**Issue by zsims** [Cimpress-MCP/serilog-sinks-awscloudwatch#53]
We haven't root-caused this yet, but we've encountered a case where the `sequenceToken` is re-used for every attempt when posting to CloudWatchLogs.

Per https://forums.aws.amazon.com/thread.jspa?messageID=651619 this could be happening due to:

> Sometimes when a web service call is made the operation is fully successful but the connection drops for some reason and the positive acknowledgement of the put isn't received by the submitting client.

Library Version: 3.0.93 (latest stable)
Stack trace:

```
2018-01-16T05:10:28.5102868Z Application starting. Selflog enabled
2018-01-18T00:54:58.4627965Z Data already accepted.  Attempt: 0  Error: Amazon.CloudWatchLogs.Model.DataAlreadyAcceptedException: The given batch of log events has already been accepted. The next batch can be sent with sequenceToken: 49579107956093934157561633466799915705921405567094496754 ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.<PublishBatchAsync>d__19.MoveNext()
2018-01-18T00:54:58.5253070Z Data already accepted.  Attempt: 1  Error: Amazon.CloudWatchLogs.Model.DataAlreadyAcceptedException: The given batch of log events has already been accepted. The next batch can be sent with sequenceToken: 49579107956093934157561633466799915705921405567094496754 ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.<PublishBatchAsync>d__19.MoveNext()
2018-01-18T00:54:58.5721289Z Data already accepted.  Attempt: 2  Error: Amazon.CloudWatchLogs.Model.DataAlreadyAcceptedException: The given batch of log events has already been accepted. The next batch can be sent with sequenceToken: 49579107956093934157561633466799915705921405567094496754 ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.<PublishBatchAsync>d__19.MoveNext()

... snip
```

**Comment by wparad** [comment]
If that happens we catch it [here](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs#L251) and the next attempt should use a new token.

I would expect if the sequence token is being reused more than once, or failed to update the token you would see `Unable to update log stream sequence`.

We can't prevent the drop.  The question becomes what caused the drop and was it recorded.

To check this, please look to find an exception before this log.  I would expect if the connection failed to close properly and get an updated sequence token then there would be another `Serilog.SelfLog` log statement logged.  Perhaps a `Unhandled exception.` as on [this line](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs#L289).

If Amazon never returns this as a failure, then we can't know there is a problem until we log the second time.  If the sdk returns a failure, we should make sure to handle it correctly.  In that case, can I ask for you to look a little closer in your logs to see if there is any indication of a failure before this exception?

**Comment by zsims** [comment]
Thanks for the reply @wparad. The stack trace I pasted is the first part of the SelfLog, there's nothing else in there that indicates failure. I can post the full `SelfLog` (10k+ lines) if it helps, although it's just the same failures forever, which is either:

 1. `2018-01-18T00:54:58.7596952Z Invalid sequence token.  Attempt: 0  Error: Amazon.CloudWatchLogs.Model.InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: ...` or
 2. `2018-01-18T00:54:58.7128098Z Data already accepted.  Attempt: 5  Error: Amazon.CloudWatchLogs.Model.DataAlreadyAcceptedException: The given batch of log events has already been accepted. The next batch can be sent with sequenceToken: ...`

**Comment by wparad** [comment]
Given the errors you are getting I believe it is caused by multiple machines attempting to use the same log stream, but let investigate your configuration:
* Do you have configured a custom `ILogStreamNameProvider`
* Are you logging to the same log group or log stream from multiple threads, i.e. multiple tasks, multiple containers, multiple machines?
* I would like to see a complete set of logs the 5 full log attempts. I.e. see `Attempt: 0` through `Attempt: 5` with the full error message.  (Can you add it is a file attached rather than posting that directly in your response?)
* Could you also include your configuration for the Sink here.

**Comment by zsims** [comment]
Thanks for the follow up.

> Given the errors you are getting I believe it is caused by multiple machines attempting to use the same log stream

From the configuration we use the log group name, but each instance uses its own stream -- so we only have one writer per stream.

> Do you have configured a custom ILogStreamNameProvider or logStreamNamePrefix?

No, just the default.

> Are you logging to the same log group or log stream from multiple threads, i.e. multiple tasks, multiple containers, multiple machines?

Same group, but different streams.

Our sink configuration:

.NET Core Config JSON
```
  "Serilog": {
    "using": "OurApiAssembly",
    "write-to_Cloudwatch.logGroupName": "OurApiLogGroup",
    "write-to_Cloudwatch.batchSizeLimit": 20,
    "write-to_Cloudwatch.periodSeconds": 10,
    "minimum-level": "Information"
  },
```

And the extension to configure Serilog:

```
namespace OurApiAssembly.Logging
{
    public static class LoggerConfigurationCloudwatchExtensions
    {
        public static LoggerConfiguration Cloudwatch(this LoggerSinkConfiguration loggerSinkConfiguration, string logGroupName, int batchSizeLimit, int periodSeconds)
        {
            var options = new CloudWatchSinkOptions
            {
                BatchSizeLimit = batchSizeLimit >= 1
                    ? batchSizeLimit
                    : CloudWatchSinkOptions.DefaultBatchSizeLimit,
                Period = periodSeconds > 0
                    ? TimeSpan.FromSeconds(periodSeconds)
                    : CloudWatchSinkOptions.DefaultPeriod,
                LogEventRenderer = new CloudWatchJsonLogRenderer()
            };

            if (!string.IsNullOrWhiteSpace(logGroupName))
            {
                options.LogGroupName = logGroupName;
            }

            IAmazonCloudWatchLogs client = new AmazonCloudWatchLogsClient(Amazon.RegionEndpoint.USWest2);

            return loggerSinkConfiguration.AmazonCloudWatch(options, client);
        }
    }
}
```

> I would like to see a complete set of logs the 5 full log attempts.

See the attached log, it's the full SelfLog: 
[serilog.self.20180118.i-0440dd8edcd22b284.log](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/files/1650287/serilog.self.20180118.i-0440dd8edcd22b284.log)

**Comment by zsims** [comment]
Having a small poke, and noticed:

https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/ca53ac5c7e0fd71c71f32ab5be8f78f9d761fb8c/src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs#L301

So I dug around the `PeriodicBatchingSink`, and from reading the code I don't think this is strictly true as:

 1. There's no locking/thread synchronization on how the periodic batching sink emits batches: https://github.com/serilog/serilog-sinks-periodicbatching/blob/16c50371424f3626f75ab19b593043555b97c676/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L171
 2. The `PortableTimer` used in the periodic batching sink will happily fire the next interval concurrently with the current running interval(s): https://github.com/serilog/serilog-sinks-periodicbatching/blob/89f21b0caec0ec2bb2f0b5233b123061b8483bc6/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PortableTimer.cs#L98 (at least with the `System.Threading.Timer` timer)

An example that demonstrates how the `System.Threading.Timer` will create many threads:
```
class Program
{
    static void Main(string[] args)
    {
        var t = new Timer(Callback, null, 0, 1000);

        Console.ReadLine();
    }

    private static void Callback(object state)
    {
        Console.WriteLine($"HIT {Thread.CurrentThread.ManagedThreadId}");
        Console.ReadLine();
    }
}
```

I'm on the Serilog chat, and will confirm if this is the case.

**Comment by wparad** [comment]
[Look up here](https://github.com/serilog/serilog-sinks-periodicbatching/blob/89f21b0caec0ec2bb2f0b5233b123061b8483bc6/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PortableTimer.cs#L73) does the lock not work?

**Comment by zsims** [comment]
The lock is released before the handler/tick is called, so it's "theoretically" possible to enter it twice given the first emit will trigger an immediate tick but there's also a timer queued up. The threading timer documentation does state:

> The method specified for callback should be reentrant, because it is called on ThreadPool threads. The method can be executed simultaneously on two thread pool threads if the timer interval is less than the time required to execute the method, or if all thread pool threads are in use and the method is queued multiple times.

From https://msdn.microsoft.com/en-us/library/ms149618(v=vs.110).aspx Although I don't think that's the issue here... We do use ASP.NET Core which does have some different behavior re: the synchronization context: https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html

Will do some more digging, but please let us know if you find anything in the meantime 👍

**Comment by zsims** [comment]
The comment is indeed troubling. I asked on the official Gitter and it should be single threaded in all cases and not re-entrant. From my reading the change per ticket is the next due date rather than interval, although not sure how that works for "missed" or "queued" ticks.

> Create a new locking context around the cloudwatch API send so that we can ensure no two calls are made at the same time.

This seems the most reasonable, as it doesn't involve avoiding core parts of Serilog.

We haven't seen the error recently, but it could be worth adding a thread number/id to the SelfLog in case this pops up again? As this could all be a red herring. If we can avoid more thread synchronization primitives the better perf/contention will be -- although the batches are very low frequency.

**Comment by wparad** [comment]
I actually think it is better to use an `AutoResetEvent` here or a `Timer` directly, but for now putting the sync code in the library makes sense.

**Comment by wparad** [comment]
I'm thinking about [this change](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/pull/55) short term.  I haven't tested it out yet.

**Comment by zsims** [comment]
Great, thanks for the changes/fix -- much appreciated :)

**Comment by wparad** [comment]
Updated version [3.0.97](https://www.nuget.org/packages/Serilog.Sinks.AwsCloudWatch/3.0.97)
